### ISSUE TITLE
Padronizar o nome das chaves do Web.Config

### ISSUE THREAD

**Issue by robertogentile** [inovaebiz/logger#1]
Esta demanda consiste em padronizar os nomes das chaves no web.config para fácil identificação, como por exemplo:

- Logger.Ativo
- Logger.PeriodoDeArmazenagem
- Logger.DiretorioDeGravacao

**Comment by mcarvalho-inova** [comment]
Tempo para desenvolvimento: 30 min.

**Comment by mcarvalho-inova** [comment]
## Fechando a  questão
Adicionado a padronização para as chaves existentes no projeto.

**Comment by robertogentile** [comment]
Bacana! A aplicação desta normalização nos projetos (internos) que hoje usamos o logger já foi realizada ou deveremos criar uma outra issue para isto? *Se não foi feita, por favor, crie a issue no Trello do cliente para que o time possa trabalhar.

**Comment by mcarvalho-inova** [comment]
Ainda deve ser feita. Criado a issue no Trello.

**Comment by robertogentile** [comment]
Ok, cria para mim por favor.
