### ISSUE TITLE
Remover a obrigatoriedade das chaves e determinar valores padrão

### ISSUE THREAD

**Issue by robertogentile** [inovaebiz/logger#2]
Nesta demanda, deve ser feito duas atividades:

- Remover a obrigatoriedade das chaves do Web.Config e;
- Determinar valores padrão quando estas chaves (ou uma das chaves) não for declarada.

Lembrando que isto indifere se for web forms, mvc ou windows forms.

**Comment by mcarvalho-inova** [comment]
**Tempo de desenvolvimento:** 1 hora.

**Comment by mcarvalho-inova** [comment]
## Fechando questão
Removido a obrigatoriedade das chaves do **Web.Config** e definido os valores padrões para chaves vazias.

**Comment by robertogentile** [comment]
Excelente!
