### ISSUE TITLE
Criar tipificação de erro e tipo padrão

### ISSUE THREAD

**Issue by robertogentile** [inovaebiz/logger#3]
Esta tarefa consiste em criar a "tipificação do erro" cujas particularidades são:

- O logger terá os seguintes tipos de erros: Informacao, Erro, Alerta;
- O valor padrão de tipificação de erro para métodos que não terão o ENUM de tipos declarados, será o "Informacao";
- O logger terá 1 arquivo para cada tipificação de erro, por exemplo: logger.informacao.json, logger.erros.json, logger.alertas, etc;

**Comment by mcarvalho-inova** [comment]
**Tempo de desenvolvimento:** 3 horas

**Comment by mcarvalho-inova** [comment]
## Fechando questão
Criado o **Enum** informações de tipificação de erro no logger com valor padrão o Enum **Informacao** com especificação no nome do arquivo. 
Atualizado também o método que faz a limpeza para identificar o arquivo com cada Enum criado.

**Comment by robertogentile** [comment]
Ciente, excelente!
