### ISSUE TITLE
Criar condicional de log de acordo com tipificação

### ISSUE THREAD

**Issue by robertogentile** [inovaebiz/logger#4]
A atividade #3 deve ser finalizada antes desta ser iniciada.

Esta tarefa consiste em criar um condicional de log de acordo com o tipo de arquivo, algo como uma chave no web.config:

- logger.gravarlogexclusivo = "informacao, alerta"

**Comment by mcarvalho-inova** [comment]
**Tempo de desenvolvimento:** 2 horas

**Comment by mcarvalho-inova** [comment]
## Fechando questão
Foi adicionado a condição de logs exclusivos no projeto. Uma vez que a tag estiver vazia, **TODOS** os logs serão gerados.

**Comment by robertogentile** [comment]
A tag estando vazia ou não existindo dá o mesmo tratamento? Obrigado!

**Comment by mcarvalho-inova** [comment]
Sim, ela da o mesmo tratamento, pois não existindo ela retorna como null e esta sendo tratado desta forma.

**Comment by robertogentile** [comment]
Excelente! Obrigado.
