### ISSUE TITLE
Permitir a configuração de dias para gravar log através de chave do arquivo de configuração

### ISSUE THREAD

**Issue by robertogentile** [inovaebiz/logger#5]
Esta tarefa consiste em permitir que, seja possível determinar quantos dias o log (hoje fixo em 7 dias) seja armazenado antes de ser excluído.

**Comment by mcarvalho-inova** [comment]
**Tempo de desenvolvimento:** 30 min.

**Comment by mcarvalho-inova** [comment]
## Fechando questão
Foi adicionado a condição de logs por tempo (dias) determinado pelo usuário. Caso esteja vazio, o mesmo terá o valor padrão de 7 dias.
