### ISSUE TITLE
Criar mecanismo que restringe o log até o tamanho determinado no arquivo de configurações

### ISSUE THREAD

**Issue by robertogentile** [inovaebiz/logger#6]
A tarefa consiste em criar um limitador de tamanho que seja possível:

- Determinar em GB qual o limite de armazenagem;
- Uma vez que o limite de armazenagem seja alcançado o sistema faz uma limpeza em um dia todo para poder ter novamente espaço e faz isso até que tenha espaço suficiente para iniciar a gravação do log;

**Comment by mcarvalho-inova** [comment]
**Tempo de desenvolvimento:** 3 horas

**Comment by mcarvalho-inova** [comment]
## Fechando questão
Foi adicionado a condição do usuário decidir qual o tamanho limite do arquivo de log será permitido. Uma vez passado no método de limpeza, o mesmo verifica se existe algum arquivo com tamanho maior que o valor determinado e exclui o arquivo.
