### ISSUE TITLE
Alterar métodos assíncronos para que fique adequado ao .NET Framework 4

### ISSUE THREAD

**Issue by mcarvalho-inova** [inovaebiz/logger#7]
É necessário alterar as chamadas dos métodos que possuem a atribuição "async" (Framework 4.5) e adicionar uma chamada assíncrona adaptada para o framework 4.0

**Comment by mcarvalho-inova** [comment]
## Fechando questão
@robertogentile, removido os métodos ASYNC do projeto e adicionado o tratamento de tasks para cada vez que iniciar a inclusão do log no arquivo.

**Comment by robertogentile** [comment]
Muito bom @mcarvalho-inova! Você chegou a testar os métodos pós implementação?

**Comment by mcarvalho-inova** [comment]
@robertogentile, foi testado somente no próprio projeto e o retorno foi positivo. A adequação para outros projeto está sendo feita neste momento.

**Comment by robertogentile** [comment]
Excelente @mcarvalho-inova . Obrigado.
