### ISSUE TITLE
Escolher número de dias para manter o registro de Logs salvo

### ISSUE THREAD

**Issue by caioinova** [inovaebiz/logger#8]
Seria interessante manter os 7 dias por padrão de tempo no qual o Logger mantém logs salvos, mas dar a possibilidade de adicionar uma tag no .config da aplicação para definir um número de dias customizados.

Exemplo:

`<!--Aqui, o Logger guardaria 90 dias de arquivos-->`
`<add key="Logger.DiasBackup" value="90" />`

**Comment by robertogentile** [comment]
Puxa, pedi isso à 3 dias atrás, havia esquecido. Tarefa #5 .
